/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test_int;

import Interfaces.Mainbase;
import com.mysql.cj.protocol.Resultset;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pct
 */
public class day_trans extends javax.swing.JFrame {
Connection con = null;
Statement st = null;
ResultSet rs =null;
  Timer timer;
    public day_trans() {
        initComponents();
        

        ActionListener actionlistener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              Date date = new Date();
              DateFormat timeFormat = new SimpleDateFormat("yyyy-MM-dd");
              String time = timeFormat.format(date);
              jLabel_Date.setText(time);
              
            }
        };
        timer = new Timer (1000, actionlistener);
        timer.setInitialDelay(0);
        timer.start();
        
     
        getsumday();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_total1 = new javax.swing.JLabel();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_cost = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_profit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_day_trans = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel_total1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jLabel_total1);
        jLabel_total1.setBounds(250, 350, 190, 30);

        jLabel_Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jLabel_Date);
        jLabel_Date.setBounds(280, 40, 180, 30);

        jLabel_cost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_cost.setText("Cost");
        jPanel1.add(jLabel_cost);
        jLabel_cost.setBounds(250, 380, 170, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Total Income of the day     -");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 350, 171, 20);

        jLabel_profit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_profit.setText("profit");
        jPanel1.add(jLabel_profit);
        jLabel_profit.setBounds(250, 410, 130, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Total Cost for the day        -");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 380, 171, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Profit of the day                 -");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 410, 173, 20);

        jTable_day_trans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order_ID", "Description", "Quantity", "Amount", "Order_Time"
            }
        ));
        jScrollPane2.setViewportView(jTable_day_trans);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(130, 150, 470, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(day_trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(day_trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(day_trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(day_trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new day_trans().setVisible(true);
            }
        });
    }
public ArrayList<DayDay_trans> userlistdaytrans(String mama)
{
    ArrayList<DayDay_trans> usersListdaytrans = new ArrayList<>();

    try{
        
        Class.forName("com.mysql.jdbc.Driver");
        con = Mainbase.getConnection();
        st = con.createStatement();
        String query3="SELECT `Order_ID`,`Description`,`Quantity`,`Amount`,`Order_Time` FROM `order_de` WHERE  `Order_Date` LIKE '%"+mama+"%'";
        rs = st.executeQuery(query3);
     
    DayDay_trans daypresent;
    while (rs.next()){
    daypresent = new DayDay_trans(rs.getString("Order_ID"), rs.getString("Description"), rs.getInt("Quantity"), rs.getDouble("Amount"),rs.getString("Order_Time"));
    usersListdaytrans.add(daypresent);
    
    }
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
       }
    return usersListdaytrans;
}

public void finduserdaytrans(){
ArrayList<DayDay_trans> list = userlistdaytrans(jLabel_Date.getText());
DefaultTableModel model = new DefaultTableModel();
model.setColumnIdentifiers(new Object[]{"Order_ID","Description","Quantity`","Amount","Order_Time"});
Object [] row= new Object[5];
for(int i=0;i<list.size();i++){

row[0]=list.get(i).getOrder_ID();
row[1]=list.get(i).getDescription();
row[2]=list.get(i).getQuantity();
row[3]=list.get(i).getAmount();
row[4]=list.get(i).getOrder_Time();
model.addRow(row);
}
jTable_day_trans.setModel(model);


}

public void getsumday(){
    double sum = 0;
    for (int i = 0; i<jTable_day_trans.getRowCount(); i++)
    {
    sum = sum + Double.parseDouble(jTable_day_trans.getValueAt(i, 3).toString());
   //double make
    }
jLabel_total1.setText(Integer.toString((int) (sum)));
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_cost;
    private javax.swing.JLabel jLabel_profit;
    private javax.swing.JLabel jLabel_total1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_day_trans;
    // End of variables declaration//GEN-END:variables
}
