/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test_int;

import Interfaces.Mainbase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author pct
 */
public class Product_manage extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs= null;
    public Product_manage() throws SQLException {
        initComponents();
        show_user();
    }
public ArrayList<User> userlist() throws SQLException{
    ArrayList<User> usersList = new ArrayList<>();
    try{
         Class.forName("com.mysql.jdbc.Driver");
    con = Mainbase.getConnection();
    String query1="SELECT * FROM pro";
    Statement st = con.createStatement();
    ResultSet rs = st.executeQuery(query1);
    User user;
    while (rs.next()){
    user = new User (rs.getString("Key_ID"), rs.getString("Description"), rs.getDouble("Cost"), rs.getDouble("Sale_Price"));
    usersList.add(user);
    
    }
    }
    catch (ClassNotFoundException e) {
        JOptionPane.showMessageDialog(null, e);
       }
    return usersList;
}

public void show_user() throws SQLException{
ArrayList<User> list = userlist();
DefaultTableModel model =  (DefaultTableModel)jTable_pro.getModel();
Object [] row= new Object[4];
for(int i=0;i<list.size();i++){
row[0]=list.get(i).getKey_ID();
row[1]=list.get(i).getDescription();
row[2]=list.get(i).getCost();
row[3]=list.get(i).getSale_price();
model.addRow(row);
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_pro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_pro_price = new javax.swing.JTextField();
        jTextField_pro_cost = new javax.swing.JTextField();
        jTextField_Description = new javax.swing.JTextField();
        jTextField_key_id = new javax.swing.JTextField();
        jButton_delete = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_pro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Key_ID", "Description", "Cost", "Sale_Price"
            }
        ));
        jTable_pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_proMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_pro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 160));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Price            -");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Key ID          -");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Description   -");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Cost             -");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(jTextField_pro_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, 30));
        jPanel1.add(jTextField_pro_cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, 30));
        jPanel1.add(jTextField_Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, 30));
        jPanel1.add(jTextField_key_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 130, 30));

        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 70, -1));

        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 70, -1));

        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 70, -1));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        try{
        String sql ="INSERT INTO pro"
                +"(Key_ID, Description, Cost, Sale_Price)"
                +"VALUES (?,?,?,?)";
        con = Mainbase.getConnection();
        pst =con.prepareStatement(sql);
        pst.setString(1, jTextField_key_id.getText());
            pst.setString(2, jTextField_Description.getText());
                pst.setString(3, jTextField_pro_cost.getText());
                    pst.setString(4, jTextField_pro_price.getText());
        pst.executeUpdate();
        DefaultTableModel model = (DefaultTableModel)jTable_pro.getModel();
            model.setRowCount(0);
            show_user();
        JOptionPane.showMessageDialog(null, "Inserted Successfully");
         jTextField_key_id.setText(""); 
        jTextField_Description.setText("");
        jTextField_pro_cost.setText("");
            jTextField_pro_price.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jTable_proMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_proMouseClicked
        int i = jTable_pro.getSelectedRow();
        TableModel model =jTable_pro.getModel();
        jTextField_key_id.setText(model.getValueAt(i,0).toString());
        jTextField_Description.setText(model.getValueAt(i,1).toString());
        jTextField_pro_cost.setText(model.getValueAt(i,2).toString());
        jTextField_pro_price.setText(model.getValueAt(i,3).toString());
    }//GEN-LAST:event_jTable_proMouseClicked

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
       try{
            
           // int row = jTable_pro.getSelectedRow();
           // String value =(jTable_pro.getModel().getValueAt(row, 0).toString());  
        String query ="UPDATE pro SET Description=?,Cost=?,Sale_Price=? WHERE Key_ID=?";
         con = Mainbase.getConnection();
       pst =con.prepareStatement(query);
        pst.setString(4, jTextField_key_id.getText());
            pst.setString(1, jTextField_Description.getText());
              pst.setString(2,jTextField_pro_cost.getText());
                   pst.setString(3,jTextField_pro_price.getText());
        pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable_pro.getModel();
            model.setRowCount(0);
            show_user();
        JOptionPane.showMessageDialog(null, "Update successfully");
         jTextField_key_id.setText(""); 
        jTextField_Description.setText("");
        jTextField_pro_cost.setText("");
            jTextField_pro_price.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Unsuccessfull");
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
      try{ 
        String query ="DELETE FROM pro WHERE Key_ID=?";
         con = Mainbase.getConnection();
       pst =con.prepareStatement(query);
        pst.setString(1, jTextField_key_id.getText());
        pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable_pro.getModel();
            model.setRowCount(0);
            show_user();
        JOptionPane.showMessageDialog(null, "Successfully Deleted");
         jTextField_key_id.setText(""); 
        jTextField_Description.setText("");
        jTextField_pro_cost.setText("");
            jTextField_pro_price.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Unsuccessfull");
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField_key_id.setText(""); 
        jTextField_Description.setText("");
        jTextField_pro_cost.setText("");
            jTextField_pro_price.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Product_manage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_pro;
    private javax.swing.JTextField jTextField_Description;
    private javax.swing.JTextField jTextField_key_id;
    private javax.swing.JTextField jTextField_pro_cost;
    private javax.swing.JTextField jTextField_pro_price;
    // End of variables declaration//GEN-END:variables
}
