/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test_int;

import Interfaces.Mainbase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author pct
 */
public class Weddings extends javax.swing.JFrame {
  Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs= null;

  
    /**
     * Creates new form Weddings
     */
    public Weddings() throws SQLException {
        initComponents();
              show_userwed();
    }
public ArrayList<wed> userlistwed() throws SQLException{
    ArrayList<wed> usersListwed = new ArrayList<>();
    try{
         Class.forName("com.mysql.jdbc.Driver");
    con = Mainbase.getConnection();
    String query2="SELECT Wedding_ID,Customer_name,Location,Wedding_date,Telephone,Shooting_time FROM weddings order by Wedding_date";
    Statement st = con.createStatement();
    ResultSet rs = st.executeQuery(query2);
    wed wedd;
    while (rs.next()){
    wedd = new wed (rs.getInt("Wedding_ID"),rs.getString("Customer_name"), rs.getString("Location"), rs.getString("Wedding_date"), rs.getInt("Telephone"), rs.getString("Shooting_time"));
    usersListwed.add(wedd);
    
    }
    }
    catch (ClassNotFoundException e) {
        JOptionPane.showMessageDialog(null, e);
       }
    return usersListwed;
}

public void show_userwed() throws SQLException{
ArrayList<wed> list = userlistwed();
DefaultTableModel model =  (DefaultTableModel)jTable_wed.getModel();
Object [] row= new Object[6];
for(int i=0;i<list.size();i++){
row[0]=list.get(i).getWedding_ID();
row[1]=list.get(i).getCustomer_name();
row[2]=list.get(i).getLocation();
row[3]=list.get(i).getWedding_date();
row[4]=list.get(i).getTelephone();
row[5]=list.get(i).getShooting_time();
model.addRow(row);
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_wed = new javax.swing.JTable();
        jTextField_searchnamewed = new javax.swing.JTextField();
        jButton1_searchwed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_wed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer_name", "Location", "Wedding_date", "Telephone", "Shooting_time"
            }
        ));
        jTable_wed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_wedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_wed);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 620, 200));
        jPanel1.add(jTextField_searchnamewed, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 100, 30));

        jButton1_searchwed.setText("Search");
        jButton1_searchwed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_searchwedActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_searchwed, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_wedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_wedMouseClicked
        int i = jTable_wed.getSelectedRow();
        TableModel model =jTable_wed.getModel();
        jTextField_searchnamewed.setText(model.getValueAt(i,1).toString());
    }//GEN-LAST:event_jTable_wedMouseClicked

    private void jButton1_searchwedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_searchwedActionPerformed
          

          finduser();                                       

    }//GEN-LAST:event_jButton1_searchwedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Weddings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Weddings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Weddings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Weddings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Weddings().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Weddings.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
public ArrayList<wed> userlist3(String wed)
{
    ArrayList<wed> usersList3 = new ArrayList<>();

    try{
        
        Class.forName("com.mysql.jdbc.Driver");
        con = Mainbase.getConnection();
        Statement st = con.createStatement();
        String query2="SELECT `Wedding_ID`,`Customer_name`,`Location`,`Wedding_date`,`Telephone`,`Shooting_time` FROM `weddings` WHERE `Customer_name` LIKE '%"+wed+"%'";
        rs = st.executeQuery(query2);
     
    wed wed1;
    while (rs.next()){
    wed1 = new wed (rs.getInt("Wedding_ID"),rs.getString("Customer_name"), rs.getString("Location"), rs.getString("Wedding_date"), rs.getInt("Telephone"),rs.getString("Shooting_time"));
    usersList3.add(wed1);
    
    }
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
       }
    return usersList3;
}

public void finduser(){
ArrayList<wed> list = userlist3(jTextField_searchnamewed.getText());
DefaultTableModel model = new DefaultTableModel();
model.setColumnIdentifiers(new Object[]{"Wedding_ID","Customer_name","Location","Wedding_date","Trlrphone","Shooting_time"});
Object [] row= new Object[6];
for(int i=0;i<list.size();i++){

row[0]=list.get(i).getWedding_ID();
row[1]=list.get(i).getCustomer_name();
row[2]=list.get(i).getLocation();
row[3]=list.get(i).getWedding_date();
row[4]=list.get(i).getTelephone();
row[5]=list.get(i).getShooting_time();
model.addRow(row);
}
jTable_wed.setModel(model);


}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_searchwed;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_wed;
    private javax.swing.JTextField jTextField_searchnamewed;
    // End of variables declaration//GEN-END:variables
}
