/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import Interfaces.Mainbase;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import test_int.Product_manage;

/**
 *
 * @author pct
 */
public class searchorder extends javax.swing.JFrame {
Connection con =null;
PreparedStatement pst =null;
Statement st=null;
ResultSet rs=null;
    
    public searchorder() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size =toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_orderID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6_amount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel3_tele = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel4_date1 = new javax.swing.JLabel();
        jButton_search = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel5_descri1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3_cusname2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6_quani1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 390));
        setPreferredSize(new java.awt.Dimension(400, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Amount    -");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 20));

        jTextField_orderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_orderIDKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_orderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Order ID -");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 20));
        jPanel1.add(jLabel6_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 110, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Telephone no. -");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 20));
        jPanel1.add(jLabel3_tele, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 110, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Date       -");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 20));
        jPanel1.add(jLabel4_date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 110, 20));

        jButton_search.setText("Search");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Description     -");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, 20));
        jPanel1.add(jLabel5_descri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 340, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Customer Name  -");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, 20));
        jPanel1.add(jLabel3_cusname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 110, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Quantity    -");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 140, 20));
        jPanel1.add(jLabel6_quani1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 110, 20));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 570, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
     try{
    String qq = jTextField_orderID.getText();
            String sql ="SELECT `Name`,`TP_No` FROM `customer` WHERE `Order_ID`='"+qq+"'";
           // String sql1 ="SELECT `Description`,`Quantity`,`Amount`,`Order_Date` FROM `order_de` WHERE `Order_ID`='"+qq+"'";
            con = Mainbase.getConnection();
            st =con.createStatement();
     
            rs=st.executeQuery(sql);
           // rs=st.executeQuery(sql1);
             while(rs.next()) { 
            jLabel3_cusname2.setText(rs.getString("Name"));     
            jLabel3_tele.setText(rs.getString("TP_No"));
            //jLabel5_descri1.setText(rs.getString("Description"));
          //  jLabel6_quani1.setText(rs.getString("Quantity"));
           // jLabel6_amount.setText(rs.getString("Amount"));
           // jLabel4_date1.setText(rs.getString("Order_Date"));
            }
     }catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
     try{
    String dd = jTextField_orderID.getText();
     String sql1 ="SELECT `Description`,`Quantity`,`Amount`,`Order_Date` FROM `order_de` WHERE `Order_ID`='"+dd+"'";
      con = Mainbase.getConnection();
            st =con.createStatement();
      rs=st.executeQuery(sql1);
       while(rs.next()) { 
           jLabel5_descri1.setText(rs.getString("Description"));
            jLabel6_quani1.setText(rs.getString("Quantity"));
            jLabel6_amount.setText(rs.getString("Amount"));
            jLabel4_date1.setText(rs.getString("Order_Date"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
       
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jTextField_orderIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_orderIDKeyPressed
       int key=evt.getKeyCode();
        if(key==10){
           try{
    String qq = jTextField_orderID.getText();
            String sql ="SELECT `Name`,`TP_No` FROM `customer` WHERE `Order_ID`='"+qq+"'";
           // String sql1 ="SELECT `Description`,`Quantity`,`Amount`,`Order_Date` FROM `order_de` WHERE `Order_ID`='"+qq+"'";
            con = Mainbase.getConnection();
            st =con.createStatement();
     
            rs=st.executeQuery(sql);
           // rs=st.executeQuery(sql1);
             while(rs.next()) { 
            jLabel3_cusname2.setText(rs.getString("Name"));     
            jLabel3_tele.setText(rs.getString("TP_No"));
            //jLabel5_descri1.setText(rs.getString("Description"));
          //  jLabel6_quani1.setText(rs.getString("Quantity"));
           // jLabel6_amount.setText(rs.getString("Amount"));
           // jLabel4_date1.setText(rs.getString("Order_Date"));
            }
     }catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
     try{
    String dd = jTextField_orderID.getText();
     String sql1 ="SELECT `Description`,`Quantity`,`Amount`,`Order_Date` FROM `order_de` WHERE `Order_ID`='"+dd+"'";
      con = Mainbase.getConnection();
            st =con.createStatement();
      rs=st.executeQuery(sql1);
       while(rs.next()) { 
           jLabel5_descri1.setText(rs.getString("Description"));
            jLabel6_quani1.setText(rs.getString("Quantity"));
            jLabel6_amount.setText(rs.getString("Amount"));
            jLabel4_date1.setText(rs.getString("Order_Date"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
       
        }if(key==27){  
        setVisible(false);
        }
       
    }//GEN-LAST:event_jTextField_orderIDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new searchorder().setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_search;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_cusname2;
    private javax.swing.JLabel jLabel3_tele;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_date1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5_descri1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6_amount;
    private javax.swing.JLabel jLabel6_quani1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_orderID;
    // End of variables declaration//GEN-END:variables
}
