/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sub_interface;

import Interfaces.Mainbase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author pct
 */
public class Admin_manage extends javax.swing.JFrame {
Connection con =null;
PreparedStatement pst =null;
ResultSet rs=null;
Statement st = null;
   
    public Admin_manage() throws SQLException {
        initComponents();
        show_useradmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jLabel_ID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_admin = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Admin Manage");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 190, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Password            -");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 30));

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 160, 30));
        jPanel2.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 160, 30));

        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel_ID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_ID.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jLabel_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 50, 30));

        jTable_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username"
            }
        ));
        jTable_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_adminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_admin);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 380, 90));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Username           -");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_adminMouseClicked
        int i = jTable_admin.getSelectedRow();
        TableModel model =jTable_admin.getModel();
        jLabel_ID.setText(model.getValueAt(i,0).toString());
    }//GEN-LAST:event_jTable_adminMouseClicked

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        try{
            String sql1 ="DELETE FROM login WHERE ID=?";
            con = Mainbase.getConnection();
            pst =con.prepareStatement(sql1);
            pst.setString(1,  jLabel_ID.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable_admin.getModel();
            model.setRowCount(0);
            show_useradmin();
            jLabel_ID.setText(null);
            JOptionPane.showMessageDialog(null, "User deleted successfuly");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Unsuccessful");
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        try{
            String sql ="INSERT INTO login"
            +"(username, password)"
            +"VALUES (?,?)";
            con = Mainbase.getConnection();
            pst =con.prepareStatement(sql);
            pst.setString(1, jTextField_username.getText());
            pst.setString(2,  Password.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable_admin.getModel();
            model.setRowCount(0);
            show_useradmin();
            JOptionPane.showMessageDialog(null, "User added successfuly");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Unsuccessful");
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Admin_manage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Admin_manage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
public ArrayList<admin_login> userlistadmin() throws SQLException{
    ArrayList<admin_login> usersListadmin = new ArrayList<>();
    try{
         Class.forName("com.mysql.jdbc.Driver");
    con = Mainbase.getConnection();
    String query1="SELECT ID, username FROM login";
    Statement st = con.createStatement();
    ResultSet rs = st.executeQuery(query1);
    admin_login user;
    while (rs.next()){
    user = new admin_login (rs.getInt("ID"), rs.getString("username"));
    usersListadmin.add(user);
    
    }
    }
    catch (ClassNotFoundException e) {
        JOptionPane.showMessageDialog(null, e);
       }
    return usersListadmin;
}
//product table
public void show_useradmin() throws SQLException{
ArrayList<admin_login> listproduct = userlistadmin();
DefaultTableModel model =  (DefaultTableModel)jTable_admin.getModel();
Object [] row= new Object[4];
for(int i=0;i<listproduct.size();i++){
row[0]=listproduct.get(i).getID();
row[1]=listproduct.get(i).getusername();
model.addRow(row);
}

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Password;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_admin;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
