/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sub_interface;

import Interfaces.Home;
import Interfaces.Mainbase;
import Interfaces.Mainbase;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import test_int.Product_manage;

/**
 *
 * @author pct
 */
public class Wedding_info extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pst=null;
Statement st=null;
ResultSet rs=null;
    
    public Wedding_info() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size =toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
       //jLabel_wedid==Home.id;
      jPanel_backpay.setBackground(new Color(0,0,0,150));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField3_Advance = new javax.swing.JTextField();
        jTextField2_Balance = new javax.swing.JTextField();
        jTextField4_Package_total = new javax.swing.JTextField();
        jTextField_locationhomecomming = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField_shttimehomecomming = new javax.swing.JTextField();
        jComboBox_package = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField_location1 = new javax.swing.JTextField();
        jTextField_shttime = new javax.swing.JTextField();
        jTextField_telephone = new javax.swing.JTextField();
        jTextField_customername = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jDateChooser_wedding = new com.toedter.calendar.JDateChooser();
        jDateChooser_homecomming = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jTextField_wedid = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jTextField_prutime = new javax.swing.JTextField();
        txt_type = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton_printinfo = new javax.swing.JButton();
        jPanel_backpay = new javax.swing.JPanel();
        jButton_show_wed = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel_background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_weddinginfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 510));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextField3_Advance, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 100, -1));
        jPanel2.add(jTextField2_Balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 100, -1));
        jPanel2.add(jTextField4_Package_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 100, -1));

        jTextField_locationhomecomming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_locationhomecommingActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_locationhomecomming, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 130, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Payment Details ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 220, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Balance                            -");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 250, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Advance                          -");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 220, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Package Total                 -");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 220, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Telephone num                  -");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Homecomming Details");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 190, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Shooting time                    - ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 190, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Shooting time                    - ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Location                            -");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 180, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Wedding Details");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 20));

        jTextField_shttimehomecomming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_shttimehomecommingActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_shttimehomecomming, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 130, 30));

        jComboBox_package.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Package 1", "Package 2", "Package 3", "Package 4" }));
        jComboBox_package.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_packageActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox_package, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Homecomming Date         - ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 190, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Type                                  -");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Wedding Date                   -");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 190, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Package                             - ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Location                            -");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 240, 30));

        jTextField_location1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_location1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_location1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 130, 30));

        jTextField_shttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_shttimeActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_shttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 130, 30));

        jTextField_telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telephoneActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, 30));

        jTextField_customername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_customernameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_customername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Wedding ID  -");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 20));

        jDateChooser_wedding.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(jDateChooser_wedding, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 130, 30));

        jDateChooser_homecomming.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(jDateChooser_homecomming, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 130, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Poruwa ceremony time      -");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 200, 10));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Address                             -");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, 20));
        jPanel2.add(jTextField_wedid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 30));

        jTextField_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addressActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 30));

        jTextField_prutime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_prutimeActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_prutime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 130, 30));
        jPanel2.add(txt_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 210, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Name                                -");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 20));

        jButton_printinfo.setText("Print Info");
        jButton_printinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_printinfoActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_printinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        javax.swing.GroupLayout jPanel_backpayLayout = new javax.swing.GroupLayout(jPanel_backpay);
        jPanel_backpay.setLayout(jPanel_backpayLayout);
        jPanel_backpayLayout.setHorizontalGroup(
            jPanel_backpayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel_backpayLayout.setVerticalGroup(
            jPanel_backpayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel_backpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 410, 210));

        jButton_show_wed.setText("Show");
        jButton_show_wed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_wedActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_show_wed, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        jLabel_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CM-3976edt.jpg"))); // NOI18N
        jPanel2.add(jLabel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 510));

        jTextArea_weddinginfo.setColumns(20);
        jTextArea_weddinginfo.setRows(5);
        jScrollPane1.setViewportView(jTextArea_weddinginfo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 46, 780, 450));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 820, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_locationhomecommingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_locationhomecommingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_locationhomecommingActionPerformed

    private void jTextField_shttimehomecommingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_shttimehomecommingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_shttimehomecommingActionPerformed

    private void jComboBox_packageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_packageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_packageActionPerformed

    private void jTextField_location1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_location1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_location1ActionPerformed

    private void jTextField_shttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_shttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_shttimeActionPerformed

    private void jTextField_telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telephoneActionPerformed

    private void jTextField_customernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_customernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_customernameActionPerformed

    private void jTextField_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addressActionPerformed

    private void jTextField_prutimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_prutimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_prutimeActionPerformed

    private void jButton_show_wedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_wedActionPerformed
try{
    String qq = jTextField_wedid.getText();
            String sql ="SELECT * from weddings WHERE Wedding_ID='"+qq+"'";
            con = Mainbase.getConnection();
            st =con.createStatement();
     
            rs=st.executeQuery(sql);
             while(rs.next()) { 
            jTextField_wedid.setText(rs.getString("Wedding_ID"));     
            jTextField_customername.setText(rs.getString("Customer_name"));
            jTextField_location1.setText(rs.getString("Location"));
            jComboBox_package.setSelectedItem(rs.getString("Package"));
           // String typ = rs.getString("Type");
          txt_type.setText(rs.getString("Type"));
           // if(typ=="Photography"){
            
              /* if(typ=="Videography"){
              jCheckBox_videography.setSelected(true);
              }if(typ=="Photography" && typ=="Videography"){
              jCheckBox_photography.setSelected(true);
              jCheckBox_videography.setSelected(true);
              }*/
   jDateChooser_wedding.setDate(rs.getDate("Wedding_date"));
   jDateChooser_homecomming.setDate(rs.getDate("Homecomming_date"));
   jTextField_shttime.setText(rs.getString("Shooting_time")); 
   jTextField_prutime.setText(rs.getString("Poruwa_time"));
   jTextField_address.setText(rs.getString("Address"));
   jTextField_telephone.setText(rs.getString("Telephone"));       
   jTextField_locationhomecomming.setText(rs.getString("Homecomming_location"));
   jTextField_shttimehomecomming.setText(rs.getString("Homecomming_shootingtime"));         
 
             }
        } catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
try{
    String dd = jTextField_wedid.getText();
            String sql ="SELECT * from wedding_pay WHERE Wedding_ID='"+dd+"'";
            con = Mainbase.getConnection();
            st =con.createStatement();
     
            rs=st.executeQuery(sql);
             while(rs.next()) { 
            jTextField4_Package_total.setText(rs.getString("Total"));     
          jTextField3_Advance.setText(rs.getString("Advance"));
          
    }//GEN-LAST:event_jButton_show_wedActionPerformed
 String n1=jTextField4_Package_total.getText();
             String n2=jTextField3_Advance.getText();
              double a= Double.parseDouble(n1);
        double b=Double.parseDouble(n2);
      double d= a-b;
        
        String c=String.valueOf(d);
        jTextField2_Balance.setText(c);
}  catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void jButton_printinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_printinfoActionPerformed
       setbill();
    try {
        jTextArea_weddinginfo.print();
    } catch (PrinterException ex) {
        Logger.getLogger(Wedding_info.class.getName()).log(Level.SEVERE, null, ex);
    }
    jTextArea_weddinginfo.setText(null);
    }//GEN-LAST:event_jButton_printinfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        String sql ="UPDATE `weddings` SET `Customer_name`=?,`Location`=?,`Package`=?,`Type`=?,`Wedding_date`=?,`Homecomming_date`=?,`Shooting_time`=?,"
                + "`Poruwa_time`=?,"
                + "`Address`=?,`Telephone`=?,`Homecomming_location`=?,"
                + "`Homecomming_shootingtime`=? WHERE `Wedding_ID`=?";
        con = Mainbase.getConnection();
        pst =con.prepareStatement(sql);
        pst.setString(1, jTextField_customername.getText());
            pst.setString(2,  jTextField_location1.getText());
            String pkg;
            pkg = jComboBox_package.getSelectedItem().toString();
                pst.setString(3, pkg);
        
                pst.setString(4, txt_type.getText());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String weddate = sdf.format(jDateChooser_wedding.getDate());
                 pst.setString(5, weddate);
                  SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                String homedate = sdf1.format(jDateChooser_homecomming.getDate());
                 pst.setString(6, homedate);
                  pst.setString(7, jTextField_shttime.getText());
            pst.setString(8,  jTextField_prutime.getText());
              pst.setString(9, jTextField_address.getText());
            pst.setString(10,  jTextField_telephone.getText());
            pst.setString(11, jTextField_locationhomecomming.getText());
            pst.setString(12, jTextField_shttimehomecomming.getText());
            pst.setString(13, jTextField_wedid.getText());
        pst.executeUpdate();

      
   
        } catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, "Error");
        }
      try{
      String sql1 ="UPDATE `wedding_pay` SET `Total`=?,`Advance`=? WHERE `Wedding_ID`=?";
       con = Mainbase.getConnection();
        pst =con.prepareStatement(sql1);
        pst.setString(1, jTextField4_Package_total.getText());
            pst.setString(2,  jTextField3_Advance.getText());
            pst.setString(3, jTextField_wedid.getText());
             pst.executeUpdate();  
             String n1=jTextField4_Package_total.getText();
             String n2=jTextField3_Advance.getText();
              double a= Double.parseDouble(n1);
        double b=Double.parseDouble(n2);
      double d= a-b;
        
        String c=String.valueOf(d);
        jTextField2_Balance.setText(c);
             JOptionPane.showMessageDialog(null, "Updated Successfully");
      }catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wedding_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wedding_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wedding_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wedding_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wedding_info().setVisible(true);
               
            }
   
        });
    }
private void setbill(){
              Date date1 = jDateChooser_wedding.getDate();
              String wedDate = DateFormat.getDateInstance().format(date1);
                Date date2 = jDateChooser_homecomming.getDate();
              String hmDate = DateFormat.getDateInstance().format(date2); 
jTextArea_weddinginfo.append("\t          SARATH PHOTO & VIDEO PRODUCTION\n"+
              "\t           No. 79-1-A,  Kahatana, Henegama.\n"+
           "\t            Tel- +94 71 812 709 6 \n"+
                   "\t                     +94 77 632 456 9\n"+
                    "\t                    +94 33 225 596 9\n"+
           "\t      E-mail - sarathphoto84@gmail.com"+
           "\n------------------------------------------------------------------------------------------------------------------------------\n"+
           "  Name:"+jTextField_customername.getText()+
           "                      Address:"+jTextField_address.getText()+
           "                                Telephone No:"+jTextField_telephone.getText()+
           
          
           "\n------------------------------------------------------------------------------------------------------------------------------\n"+
           "  Wedding Info\n"+
           "  Location:"+jTextField_location1.getText()+                                
           "                               Wedding Date:"+wedDate+
           "\n\n"+
           "  Shooting Time:"+jTextField_shttime.getText()+                      
           "                      Poruwa Ceremony:"+jTextField_prutime.getText()+
           "\n\n"+
           "  Type:"+txt_type.getText()+
                                     
           "\n------------------------------------------------------------------------------------------------------------------------------\n"+
           " Homecomming Info\n"+ 
           " Location:"+jTextField_locationhomecomming.getText()+
           "                      Homecomming Date:"+hmDate+           
           "\n\n"+
           " Homecomming Shooting Time:"+jTextField_shttimehomecomming.getText()+
           "\n------------------------------------------------------------------------------------------------------------------------------\n"+
           "        Total Price:"+"\t"+jTextField4_Package_total.getText()+"\n"+
           "        Advance:"+"\t"+"\t"+jTextField3_Advance.getText()+"\n"+
           "        Balance:"+"\t"+"\t"+jTextField2_Balance.getText()+"\n"+
           
           "\n------------------------------------------------------------------------------------------------------------------------------\n"+
           
           "                                                                              THANKYOU!!!"
           
                       );


}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_printinfo;
    private javax.swing.JButton jButton_show_wed;
    private javax.swing.JComboBox<String> jComboBox_package;
    private com.toedter.calendar.JDateChooser jDateChooser_homecomming;
    private com.toedter.calendar.JDateChooser jDateChooser_wedding;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_backpay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea_weddinginfo;
    private javax.swing.JTextField jTextField2_Balance;
    private javax.swing.JTextField jTextField3_Advance;
    private javax.swing.JTextField jTextField4_Package_total;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_customername;
    private javax.swing.JTextField jTextField_location1;
    private javax.swing.JTextField jTextField_locationhomecomming;
    private javax.swing.JTextField jTextField_prutime;
    private javax.swing.JTextField jTextField_shttime;
    private javax.swing.JTextField jTextField_shttimehomecomming;
    private javax.swing.JTextField jTextField_telephone;
    private javax.swing.JTextField jTextField_wedid;
    private javax.swing.JTextField txt_type;
    // End of variables declaration//GEN-END:variables
}
