/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.SimpleTimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import test_int.Product_manage;

/**
 *
 * @author pct
 */
public class Wedding_order extends javax.swing.JFrame {
 Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs= null;
    /**
     * Creates new form Wedding_order
     */
    public Wedding_order() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size =toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
          jPanel_backpay.setBackground(new Color(0,0,0,150));
         jTextField_name.requestFocus();
    }
//public boolean chechinputs(){




//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField3_Advance = new javax.swing.JTextField();
        jTextField2_Balance = new javax.swing.JTextField();
        jTextField4_Package_total = new javax.swing.JTextField();
        jTextField_locationhomecomming = new javax.swing.JTextField();
        jButton_reset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField_shttimehomecomming = new javax.swing.JTextField();
        jComboBox_package = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1_add_wedding = new javax.swing.JButton();
        jTextField_location1 = new javax.swing.JTextField();
        jTextField_shttime = new javax.swing.JTextField();
        jTextField_telephone = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox_photography = new javax.swing.JCheckBox();
        jCheckBox_videography = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jTextField_address = new javax.swing.JTextField();
        jTextField_prutime = new javax.swing.JTextField();
        jPanel_backpay = new javax.swing.JPanel();
        jLabel_background = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser_wedding = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser_homecomming = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3_Advance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3_AdvanceKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3_Advance, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 100, -1));
        jPanel1.add(jTextField2_Balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 100, -1));

        jTextField4_Package_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4_Package_totalKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4_Package_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 100, -1));

        jTextField_locationhomecomming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_locationhomecommingActionPerformed(evt);
            }
        });
        jTextField_locationhomecomming.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_locationhomecommingKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_locationhomecomming, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 130, 30));

        jButton_reset.setText("Reset");
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 433, 70, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Payment Details ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 220, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Balance                            -");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 250, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Advance                          -");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 220, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Package Total                 -");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 220, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Telephone num                  -");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Homecomming Details");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 190, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Shooting time                    - ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 190, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Shooting time                    - ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Location                            -");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 180, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Wedding Details");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 190, 20));

        jTextField_shttimehomecomming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_shttimehomecommingActionPerformed(evt);
            }
        });
        jTextField_shttimehomecomming.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_shttimehomecommingKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_shttimehomecomming, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 130, 30));

        jComboBox_package.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Package 1", "Package 2", "Package 3", "Package 4" }));
        jComboBox_package.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_packageActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_package, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Homecomming Date         - ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 190, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Type                                  -");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Wedding Date                   -");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Package                             - ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Location                            -");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 240, 10));

        jButton1_add_wedding.setText("Save");
        jButton1_add_wedding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add_weddingActionPerformed(evt);
            }
        });
        jButton1_add_wedding.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1_add_weddingKeyPressed(evt);
            }
        });
        jPanel1.add(jButton1_add_wedding, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 433, 80, 30));

        jTextField_location1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_location1ActionPerformed(evt);
            }
        });
        jTextField_location1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_location1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_location1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, 30));

        jTextField_shttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_shttimeActionPerformed(evt);
            }
        });
        jTextField_shttime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_shttimeKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_shttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 130, 30));

        jTextField_telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telephoneActionPerformed(evt);
            }
        });
        jTextField_telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_telephoneKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 130, 30));

        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Name                                -");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 20));

        jCheckBox_photography.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jCheckBox_photography.setForeground(new java.awt.Color(153, 153, 153));
        jCheckBox_photography.setText("Photography");
        jPanel1.add(jCheckBox_photography, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jCheckBox_videography.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jCheckBox_videography.setForeground(new java.awt.Color(153, 153, 153));
        jCheckBox_videography.setText("Videography");
        jPanel1.add(jCheckBox_videography, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Poruwa ceremony time      -");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 190, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 200, 10));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Address                             -");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, 20));

        jTextField_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addressActionPerformed(evt);
            }
        });
        jTextField_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_addressKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 30));

        jTextField_prutime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_prutimeActionPerformed(evt);
            }
        });
        jTextField_prutime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_prutimeKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_prutime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 130, 30));

        javax.swing.GroupLayout jPanel_backpayLayout = new javax.swing.GroupLayout(jPanel_backpay);
        jPanel_backpay.setLayout(jPanel_backpayLayout);
        jPanel_backpayLayout.setHorizontalGroup(
            jPanel_backpayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel_backpayLayout.setVerticalGroup(
            jPanel_backpayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel_backpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 410, 160));

        jLabel_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CM-3976edt.jpg"))); // NOI18N
        jPanel1.add(jLabel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 510));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 130, -1));
        jPanel1.add(jDateChooser_wedding, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 110, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));
        jPanel1.add(jDateChooser_homecomming, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_locationhomecommingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_locationhomecommingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_locationhomecommingActionPerformed

    private void jTextField_shttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_shttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_shttimeActionPerformed

    private void jTextField_telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telephoneActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jComboBox_packageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_packageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_packageActionPerformed

    private void jButton1_add_weddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add_weddingActionPerformed
      try{
        String sql ="INSERT INTO weddings"
                +"(Customer_name, Location, Package, Type, Wedding_date, Homecomming_date, Shooting_time, Poruwa_time, Address, Telephone, Homecomming_location, Homecomming_shootingtime)"
                +"VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
        con = Mainbase.getConnection();
        pst =con.prepareStatement(sql);
        pst.setString(1, jTextField_name.getText());
            pst.setString(2,  jTextField_location1.getText());
            String pkg;
            pkg = jComboBox_package.getSelectedItem().toString();
                pst.setString(3, pkg);
                String Type = "";
                if(jCheckBox_photography.isSelected()){
                Type+=jCheckBox_photography.getText()+" ";
                }
                if(jCheckBox_videography.isSelected()){
                Type+=jCheckBox_videography.getText()+" ";
                }
                pst.setString(4, Type);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String weddate = sdf.format(jDateChooser_wedding.getDate());
                 pst.setString(5, weddate);
                  SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                String homedate = sdf1.format(jDateChooser_homecomming.getDate());
                 pst.setString(6, homedate);
                  pst.setString(7, jTextField_shttime.getText());
            pst.setString(8,  jTextField_prutime.getText());
              pst.setString(9, jTextField_address.getText());
            pst.setString(10,  jTextField_telephone.getText());
            pst.setString(11, jTextField_locationhomecomming.getText());
            pst.setString(12, jTextField_shttimehomecomming.getText());
        pst.executeUpdate();

       // JOptionPane.showMessageDialog(null, "Inserted Successfully");
   
        } catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, "Error");
        }
      try{
      String sql1 ="INSERT INTO wedding_pay"
                   +"(Total, Advance)"
              +"VALUES (?,?)";
       con = Mainbase.getConnection();
        pst =con.prepareStatement(sql1);
        pst.setString(1, jTextField4_Package_total.getText());
            pst.setString(2,  jTextField3_Advance.getText());
             pst.executeUpdate();  
             String n1=jTextField4_Package_total.getText();
             String n2=jTextField3_Advance.getText();
              double a= Double.parseDouble(n1);
        double b=Double.parseDouble(n2);
      double d= a-b;
        
        String c=String.valueOf(d);
        jTextField2_Balance.setText(c);
             JOptionPane.showMessageDialog(null, "Inserted Successfully");
      }catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton1_add_weddingActionPerformed

    private void jTextField_prutimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_prutimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_prutimeActionPerformed

    private void jTextField_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addressActionPerformed

    private void jTextField_shttimehomecommingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_shttimehomecommingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_shttimehomecommingActionPerformed

    private void jTextField_location1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_location1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_location1ActionPerformed

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
       
        jTextField_name.setText("");
        jTextField_locationhomecomming.setText("");
        jComboBox_package.setSelectedItem(null);
        jCheckBox_photography.setSelected(false);
       jCheckBox_videography.setSelected(false);
     jDateChooser_wedding.setDate(null);
     jDateChooser_homecomming.setDate(null);
     jTextField_shttime.setText("");
     jTextField_prutime.setText("");
    jTextField_address.setText("");
    jTextField_telephone.setText("");
    jTextField_locationhomecomming.setText("");
    jTextField_shttimehomecomming.setText("");
    jTextField_location1.setText("");
    jTextField2_Balance.setText("");
    jTextField4_Package_total.setText("");
    jTextField3_Advance.setText("");
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jTextField_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
        jTextField_address.requestFocus();
        }
    }//GEN-LAST:event_jTextField_nameKeyPressed

    private void jTextField_addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_addressKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
        jTextField_location1.requestFocus();
        }
    }//GEN-LAST:event_jTextField_addressKeyPressed

    private void jTextField_location1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_location1KeyPressed
        int key=evt.getKeyCode();
        if(key==10){
       jTextField_telephone.requestFocus();
        }
    }//GEN-LAST:event_jTextField_location1KeyPressed

    private void jTextField_telephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telephoneKeyPressed
      int key=evt.getKeyCode();
        if(key==10){
       jComboBox_package.requestFocus();
        }
    }//GEN-LAST:event_jTextField_telephoneKeyPressed

    private void jDateChooser_weddingAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser_weddingAncestorAdded
        jTextField_shttime.requestFocus();
    }//GEN-LAST:event_jDateChooser_weddingAncestorAdded

    private void jTextField_shttimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_shttimeKeyPressed
          int key=evt.getKeyCode();
        if(key==10){
    jTextField_prutime.requestFocus();
        }
    }//GEN-LAST:event_jTextField_shttimeKeyPressed

    private void jTextField_prutimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_prutimeKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
 jDateChooser_homecomming.requestFocus();
        }
    }//GEN-LAST:event_jTextField_prutimeKeyPressed

    private void jDateChooser_homecommingAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser_homecommingAncestorAdded
        jTextField_locationhomecomming.requestFocus();
    }//GEN-LAST:event_jDateChooser_homecommingAncestorAdded

    private void jTextField_locationhomecommingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_locationhomecommingKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
 jTextField_shttimehomecomming.requestFocus();
        }
    }//GEN-LAST:event_jTextField_locationhomecommingKeyPressed

    private void jTextField_shttimehomecommingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_shttimehomecommingKeyPressed
         int key=evt.getKeyCode();
        if(key==10){
jTextField4_Package_total.requestFocus();
        }
    }//GEN-LAST:event_jTextField_shttimehomecommingKeyPressed

    private void jTextField4_Package_totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4_Package_totalKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
jTextField3_Advance.requestFocus();
        }
    }//GEN-LAST:event_jTextField4_Package_totalKeyPressed

    private void jTextField3_AdvanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3_AdvanceKeyPressed
      int key=evt.getKeyCode();
        if(key==10){

        jButton1_add_wedding.requestFocus();
      String n1=jTextField4_Package_total.getText();
             String n2=jTextField3_Advance.getText();
              double a= Double.parseDouble(n1);
        double b=Double.parseDouble(n2);
      double d= a-b;
        
        String c=String.valueOf(d);
        jTextField2_Balance.setText(c);
        }
    }//GEN-LAST:event_jTextField3_AdvanceKeyPressed

    private void jButton1_add_weddingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1_add_weddingKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
 try{
        String sql ="INSERT INTO weddings"
                +"(Customer_name, Location, Package, Type, Wedding_date, Homecomming_date, Shooting_time, Poruwa_time, Address, Telephone, Homecomming_location, Homecomming_shootingtime)"
                +"VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
        con = Mainbase.getConnection();
        pst =con.prepareStatement(sql);
        pst.setString(1, jTextField_name.getText());
            pst.setString(2,  jTextField_location1.getText());
            String pkg;
            pkg = jComboBox_package.getSelectedItem().toString();
                pst.setString(3, pkg);
                String Type = "";
                if(jCheckBox_photography.isSelected()){
                Type+=jCheckBox_photography.getText()+" ";
                }
                if(jCheckBox_videography.isSelected()){
                Type+=jCheckBox_videography.getText()+" ";
                }
                pst.setString(4, Type);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String weddate = sdf.format(jDateChooser_wedding.getDate());
                 pst.setString(5, weddate);
                  SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                String homedate = sdf1.format(jDateChooser_homecomming.getDate());
                 pst.setString(6, homedate);
                  pst.setString(7, jTextField_shttime.getText());
            pst.setString(8,  jTextField_prutime.getText());
              pst.setString(9, jTextField_address.getText());
            pst.setString(10,  jTextField_telephone.getText());
            pst.setString(11, jTextField_locationhomecomming.getText());
            pst.setString(12, jTextField_shttimehomecomming.getText());
        pst.executeUpdate();

       // JOptionPane.showMessageDialog(null, "Inserted Successfully");
   
        } catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, "Error");
        }
      try{
      String sql1 ="INSERT INTO wedding_pay"
                   +"(Total, Advance)"
              +"VALUES (?,?)";
       con = Mainbase.getConnection();
        pst =con.prepareStatement(sql1);
        pst.setString(1, jTextField4_Package_total.getText());
            pst.setString(2,  jTextField3_Advance.getText());
             pst.executeUpdate();  
             String n1=jTextField4_Package_total.getText();
             String n2=jTextField3_Advance.getText();
              double a= Double.parseDouble(n1);
        double b=Double.parseDouble(n2);
      double d= a-b;
        
        String c=String.valueOf(d);
        jTextField2_Balance.setText(c);
             JOptionPane.showMessageDialog(null, "Inserted Successfully");
      }catch (SQLException ex) {
            Logger.getLogger(Product_manage.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, "Error");
        }
        }
    }//GEN-LAST:event_jButton1_add_weddingKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wedding_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wedding_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wedding_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wedding_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wedding_order().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_add_wedding;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JCheckBox jCheckBox_photography;
    private javax.swing.JCheckBox jCheckBox_videography;
    private javax.swing.JComboBox<String> jComboBox_package;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser_homecomming;
    private com.toedter.calendar.JDateChooser jDateChooser_wedding;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_backpay;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2_Balance;
    private javax.swing.JTextField jTextField3_Advance;
    private javax.swing.JTextField jTextField4_Package_total;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_location1;
    private javax.swing.JTextField jTextField_locationhomecomming;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_prutime;
    private javax.swing.JTextField jTextField_shttime;
    private javax.swing.JTextField jTextField_shttimehomecomming;
    private javax.swing.JTextField jTextField_telephone;
    // End of variables declaration//GEN-END:variables
}
